# Generated by Django 4.2.4 on 2023-09-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='acc_num',
        ),
    ]
