# Generated by Django 4.2.4 on 2023-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_account_acc_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
