# Generated by Django 4.2.4 on 2023-09-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_account_acc_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='acc_num',
        ),
    ]
